CREATE DATABASE RH;
USE RH;

create table FUNCIONARIO(
	
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(255) NOT NULL,
	SALARIO FLOAT NOT NULL,
	IDADE INT NOT NULL,
	SEXO CHAR(1) NOT NULL,
	EMAIL VARCHAR(30),
	CARGO VARCHAR(15) NOT NULL
);

/*ALTERAÇÃO QUANTIDADE DE CARACTERES*/
ALTER TABLE FUNCIONARIO MODIFY COLUMN CARGO VARCHAR(50);

/*INSERÇÃO DE DADOS*/
INSERT INTO FUNCIONARIO(ID, NOME,IDADE,SEXO,EMAIL,SALARIO,CARGO) VALUES(NULL,'Gilson',31,'M','gilsondmatos@hotmail.com',12500,'Adm. Banco de Dados');
INSERT INTO FUNCIONARIO(ID, NOME,IDADE,SEXO,EMAIL,SALARIO,CARGO) VALUES(NULL,'Carlos',32,'M','carlos@hotmail.com',3500,'Gerente RH');
INSERT INTO FUNCIONARIO(ID, NOME,IDADE,SEXO,EMAIL,SALARIO,CARGO) VALUES(NULL,'Renata',23,'M','renata@hotmail.com',1500,'Auxiliar Serv.Gerais');
INSERT INTO FUNCIONARIO(ID, NOME,IDADE,SEXO,EMAIL,SALARIO,CARGO) VALUES(NULL,'Pedro',31,'M','pedro@hotmail.com',10500,'Diretor Marketing');
INSERT INTO FUNCIONARIO(ID, NOME,IDADE,SEXO,EMAIL,SALARIO,CARGO) VALUES(NULL,'Antônio',31,'M','antonio@hotmail.com',2500,'Analista de Suporte');

SELECT ID,NOME,SALARIO
FROM FUNCIONARIO
WHERE SALARIO > 2000;

SELECT ID,NOME,SALARIO
FROM FUNCIONARIO
WHERE SALARIO < 2000;

SELECT *FROM FUNCIONARIO;

UPDATE FUNCIONARIO SET SALARIO = 15000
WHERE ID = 1;








